In [3]:
import pandas as pd

df = pd.read_csv(r"C:\Users\A02047803\Desktop\DATA_5500_FA_26\in_class_code\top-10k-spotify-songs-2025-07.csv")
df

,rank,track_name,track_id,artist_names,artist_ids,album_name,album_id,popularity,duration,explicit,release_date,album_type,isrc,copies
0,1,Die With A Smile,2plbrEY59IikOBgBGLjaoe,Lady Gaga|Bruno Mars,1HY2Jd0NmPuamShAr6KMms|0du5cEVh5yTK9QJze8zA0C,Die With A Smile,10FLjwfpbxLmW8c25Xyc2N,100,4:11,0,8/16/2024,single,USUM72409273,9
1,2,DtMF,3sK8wGT43QFpWrvNQsrQya,Bad Bunny,4q3ewBCX7sLwd24euuV69X,DeBÍ TiRAR MáS FOToS,5K79FLRUCSysQnVESLcTdb,98,3:57,1,1/5/2025,album,QMFMF2447070,3
2,3,BIRDS OF A FEATHER,6dOtVTDdiauQNBQEDOtlAB,Billie Eilish,6qqNVTkY8uBg9cP3Jd7DAH,HIT ME HARD AND SOFT,7aJuG4TFXa2hmE4z1yxc3n,98,3:30,0,5/17/2024,album,USUM72401994,7
3,4,Clean Baby Sleep White Noise (Loopable),0zirWZTcXBBwGsevrsIpvT,Dream Supplier|Baby Sleeps|Background White Noise,6Cqtx9fpxzggIMuKn0RGCp|48zEowASEXWsK6lgP1xotZ|...,Best White Noise For Sleeping Baby,0NGHR9zjS5eFFlqtClA9VV,97,2:22,0,4/29/2020,single,NLC8M2000219,2
4,5,BAILE INoLVIDABLE,2lTm559tuIvatlT1u0JYG2,Bad Bunny,4q3ewBCX7sLwd24euuV69X,DeBÍ TiRAR MáS FOToS,5K79FLRUCSysQnVESLcTdb,96,6:07,1,1/5/2025,album,QMFMF2447057,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,9996,Gamesofluck,0rdWkO7ncrh1lrJGDmLq9L,Parcels,3oKRxpszQKUjjaHz388fVA,Gamesofluck,0ugE0qpkFDNLYFmNiUOOKA,70,5:48,0,10/28/2016,single,FRU701600048,4
9996,9997,Casio,44ZKnfWEkp7wPs035j4Tua,Jungle,59oA5WbbQvomJz2BuRG071,For Ever,5gYCZgmXzzWXxOCb9fMfBm,70,3:54,0,9/14/2018,album,GBBKS1800101,4
9997,9998,FANTASTIC BABY - Japanese ver.,26JeAi8xsSvLRoNsl9B8Js,BIGBANG,4Kxlr1PRlDKEB0ekOCyHgX,ALIVE,7p5rDiIXiv1IcEMThKwsaM,70,3:51,0,3/28/2012,album,JPB601211901,8
9998,9999,Miniskirt,6Yj8kVuVR3UPxx9r5eFEoV,AOA,54gWVQFHf8IIqbjxAoOarN,MINISKIRT,6esB2DBt46m38ZycDPsn8D,70,2:59,0,1/16/2014,single,KRA491400072,2
9999,10000,Backslide,6fNaHkjAxP6rI2sZhT7QJn,Twenty One Pilots,3YQKmKGau1PzlVlkL1iodx,Clancy,1KFWgQTw3EMTQebaaepVBI,70,3:00,0,5/24/2024,album,USAT22402064,133

In [7]:
# preview of your dataframe
df.head()
df.tail()

,rank,track_name,track_id,artist_names,artist_ids,album_name,album_id,popularity,duration,explicit,release_date,album_type,isrc,copies
9995,9996,Gamesofluck,0rdWkO7ncrh1lrJGDmLq9L,Parcels,3oKRxpszQKUjjaHz388fVA,Gamesofluck,0ugE0qpkFDNLYFmNiUOOKA,70,5:48,0,10/28/2016,single,FRU701600048,4
9996,9997,Casio,44ZKnfWEkp7wPs035j4Tua,Jungle,59oA5WbbQvomJz2BuRG071,For Ever,5gYCZgmXzzWXxOCb9fMfBm,70,3:54,0,9/14/2018,album,GBBKS1800101,4
9997,9998,FANTASTIC BABY - Japanese ver.,26JeAi8xsSvLRoNsl9B8Js,BIGBANG,4Kxlr1PRlDKEB0ekOCyHgX,ALIVE,7p5rDiIXiv1IcEMThKwsaM,70,3:51,0,3/28/2012,album,JPB601211901,8
9998,9999,Miniskirt,6Yj8kVuVR3UPxx9r5eFEoV,AOA,54gWVQFHf8IIqbjxAoOarN,MINISKIRT,6esB2DBt46m38ZycDPsn8D,70,2:59,0,1/16/2014,single,KRA491400072,2
9999,10000,Backslide,6fNaHkjAxP6rI2sZhT7QJn,Twenty One Pilots,3YQKmKGau1PzlVlkL1iodx,Clancy,1KFWgQTw3EMTQebaaepVBI,70,3:00,0,5/24/2024,album,USAT22402064,133

In [10]:
df.columns
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 14 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   rank          10000 non-null  int64
 1   track_name    10000 non-null  object
 2   track_id      10000 non-null  object
 3   artist_names  10000 non-null  object
 4   artist_ids    10000 non-null  object
 5   album_name    9999 non-null   object
 6   album_id      10000 non-null  object
 7   popularity    10000 non-null  int64
 8   duration      10000 non-null  object
 9   explicit      10000 non-null  int64
 10  release_date  10000 non-null  object
 11  album_type    10000 non-null  object
 12  isrc          10000 non-null  object
 13  copies        10000 non-null  int64
dtypes: int64(4), object(10)
memory usage: 1.1+ MB

In [11]:
df.describe()

              rank    popularity      explicit        copies
count  10000.00000  10000.000000  10000.000000  10000.000000
mean    5000.50000     75.065700      0.263800     70.089300
std     2886.89568      4.348388      0.440714    169.137545
min        1.00000     70.000000      0.000000      1.000000
25%     2500.75000     72.000000      0.000000      2.000000
50%     5000.50000     74.000000      0.000000      6.000000
75%     7500.25000     77.000000      1.000000     47.000000
max    10000.00000    100.000000      1.000000   2655.000000

In [14]:
df[["copies", "track_name"]]

      copies                               track_name
0          9                         Die With A Smile
1          3                                     DtMF
2          7                       BIRDS OF A FEATHER
3          2  Clean Baby Sleep White Noise (Loopable)
4          1                        BAILE INoLVIDABLE
...      ...                                      ...
9995       4                              Gamesofluck
9996       4                                    Casio
9997       8           FANTASTIC BABY - Japanese ver.
9998       2                                Miniskirt
9999     133                                Backslide

[10000 rows x 2 columns]

In [15]:
total_copies = df["copies"].sum()
total_copies

np.int64(700893)

In [23]:
em_df = df[(df["explicit"] == 1) & (df["rank"] > 9800)]
em_df

,rank,track_name,track_id,artist_names,artist_ids,album_name,album_id,popularity,duration,explicit,release_date,album_type,isrc,copies
9800,9801,Toyota (2016),6rdy1vGWSpfPxKnHujzMmY,Bonez MC,1aS5tqEs9ci5P9KD9tZWa6,Toyota (2016),6Wq84hoViqD2GBVqqVAaQJ,70,2:39,1,12/26/2024,single,DECE72402929,5
9801,9802,EIN TEIL VON MIR,0JtDPZDAIEIZbE1y7aSjTB,badchieff,6GoNVmYCl0yUm4pEp80vn6,EIN TEIL VON MIR,04NdFbXkgiLxxemKACJIHd,70,2:45,1,1/31/2025,single,DEQ322500016,4
9802,9803,BONSAI,6pTDI0xC9njboSOZoiMgU5,Ak4:20|En La Nota Records,1SiLK8gdECx2iEm2SSj0Bl|0fYYFdqW44JKqmBPSHX1c2,BONSAI,015nwEsUaD2okzr62ieqSm,70,2:13,1,2/5/2025,single,BK4DA2503424,1
9803,9804,Volando,1aHD6BlYi6rsJCetEWH9f4,Lefty Sm,6eXHRfK9Ad3IpMpSAqvcDf,Volando,3h9sn7qACkviYYhvey79hp,70,3:38,1,11/16/2020,single,USANG2102659,1
9804,9805,Por Mi México,2sUknbm8xdLQgH7wb8xcTX,Lefty Sm|Santa Fe Klan,6eXHRfK9Ad3IpMpSAqvcDf|4tm8CEdm4pkQsEh4jIr9Yp,Necesidad,7iSPRgLrTrRr7Ed5W2tws6,70,3:38,1,6/19/2020,album,USHM22005503,1
9807,9808,Lean,44BZWegR2TBYtgZdAHwaGH,Super Yei|Sammy|Jone Quest|Towy|Osquel|Beltito...,6HqgxkTt9KGyt27zYrwVan|2raERfjzsdnUUQeZSge5eZ|...,Lean,08MtJrm31CA8dV2txpLMXE,70,4:20,1,3/31/2017,single,TCACZ1798112,5
9813,9814,4Tal,6OcZP4rUfuxms2r8Mwx5BQ,Matuê|Teto,5nP8x4uEFjAAmDzwOEc9b8|68YeXpLt3jB7JHQS5ZjMGo,333,5CP84pfi4AFe95UTACFWrk,70,3:24,1,9/9/2024,album,BXW922400037,1
9814,9815,Freestyle,0LGGo9eY1aJX6tqgxa87kd,KayBlack|Wall Hein|Yokame,2h5Ha0ZiMFmOQD3iYcSXsy|5wEgjH2s4SAiffRmzkBqHB|...,Freestyle,3vbB47zGSYseoxaGbZFW7p,70,3:00,1,4/28/2022,single,USLZJ2275472,1
9815,9816,Maturidade,5RHOhXxMVhpEaBcG6hIydA,KayBlack|Wall Hein|AMUSIK,2h5Ha0ZiMFmOQD3iYcSXsy|5wEgjH2s4SAiffRmzkBqHB|...,Maturidade,2QWzXzDW94VU4E9KBSJehg,70,2:22,1,9/8/2022,single,BC3PG2303400,1
9816,9817,Novo Balanço,4hKLzFvNwHF6dPosGT30ed,Veigh|Bvga Beatz|Prod Malax|Supernova Ent,4YqwRbMLqGHRHLS1w2ZKse|7saGN6a32YNpiMPo2SWJxE|...,Dos Prédios Deluxe,0D59BFMmnA87oPyk1oSe1b,70,2:20,1,5/19/2023,album,QZMWW2396002,1
9820,9821,Terapia,5ROyrHNiEx9DeZ5SONjVbM,Mc Kevin,5pBMkZNIlbGTH3hrsQJqAa,Terapia,2ggZO9M8nzvY5si8MyyZUy,70,3:32,1,4/6/2020,single,BXG6R2000430,1
9822,9823,Gaiola É o Troco,3Uq45ipGutypFPmETfaoaH,MC Du Black|DJ 2F,6v4PBIzRAGaLp43LVureQc|3tkq9ZnBaejLPLRpg8kGET,Gaiola É o Troco,015kXzs5wCoiKyNQBPy19d,70,3:07,1,6/7/2019,single,BX0SO1900185,1
9832,9833,9$IDE x Amethyst,2nmkR3ofEwOzN24TJ9LynR,Tory Lanez,2jku7tDXc6XoB6MO2hFuqg,PETERSON,6QoJa1uhryvCmMlmq0BCJQ,70,3:42,1,3/7/2025,album,QZJ842500905,2
9833,9834,Lovers And Friends,41PWz0hAiU9FqsmjR9Wh62,Lil Jon & The East Side Boyz|USHER|Ludacris,3ciRvbBIVz9fBoPbtSYq4x|23zg3TcAtWQy7J6upgbUnj|...,Crunk Juice,0hk2hXNB5d65F400dhcdcV,70,4:20,1,11/16/2004,album,USTV10400221,4
9834,9835,Fine China,5274I4mUMnYczyeXkGDWZN,Future|Juice WRLD,1RyvyyTE3xzB2ZywiAwp0i|4MCBfE4596Uoi2O4DtmEMz,Future & Juice WRLD Present... WRLD ON DRUGS,6P9PZjWXoCRF5b66BafPKY,70,2:21,1,10/19/2018,album,USSM11808143,2
9835,9836,PSA,6T5i0o62ZyfHRRHHihYJ1n,Kay Flock,2AMeiDbfU2vonrTkpXDKUu,The D.O.A. Tape,5DMfgmlbRD0HeUi5QQgOAD,70,1:53,1,11/5/2021,album,USUM72120731,8
9836,9837,Vroom Vroom,5hyq3LBlCfjRQAFkdQwe8o,Charli xcx,25uiPmTg16RbhZWAqwLBy5,Vroom Vroom EP,261QvR3MgGdyL2HyYIlgfd,70,3:13,1,2/26/2016,single,GBAHS1600092,84
9841,9842,mewtwo,6xZYGIixR3zhhOHwu7UEMY,Ken Carson,3gBZUcNeVumkeeJ19CY2sX,A Great Chaos (Deluxe),58iEeJbYd6OBGRM0TiwltL,70,2:08,1,7/5/2024,album,USUM72403585,1
9842,9843,NOSTYLIST,0MXemkrh7WpAfiafcGQwZO,Destroy Lonely,1HPW4jeRjXBFRoUnSvBzoD,NO STYLIST,0G4XTKDAeBmdfV8pZFaYu2,70,3:00,1,8/12/2022,album,USLD91740130,3
9845,9846,killer queen,2ubQc1V6ctD8YpRjP5H940,Mad Tsai,5C2iFRY2UldL2hv9THw4aB,killer queen,1M4yS3Ek9N8g63Nj86fZsN,70,2:58,1,10/29/2021,single,QZNWV2111785,5
9849,9850,SORRY NOT SORRY,410ZZP746AQeiywhKvXWCo,"Tyler, The Creator",4V8LLVI7PbaPR0K2TGSxFF,CALL ME IF YOU GET LOST: The Estate Sale,1GG6U2SSJPHO6XsFiBzxYv,70,3:26,1,3/31/2023,album,USQX92301939,1
9850,9851,Cooped Up / Return Of The Mack,6Ole34qqbgkZ60IyrcVm7e,Post Malone|Mark Morrison|Sickick,246dkjvS1zLTtiykXe5h60|6V3F8MZrOKdT9fU686ybE9|...,Cooped Up / Return Of The Mack,4G0HO7POrjMX9cKLX2KxkF,70,2:07,1,10/21/2022,single,USUM72218744,9
9875,9876,WER MACHT PARA 3,1XhEwA9KL44MtKNfHEc2NJ,Eno|Dardan|Daniel Slump,3GBBxBdoolb0B5YizZq9bF|3pjq2pDV9RR6VY55wBjVnp|...,WER MACHT PARA 3,1myLq2BFzmGEPqReRp6BUh,70,2:26,1,2/21/2025,single,DEA622500528,4
9887,9888,Aerolínea Carrillo,0xYTyyfV767E2Vn3hz56kL,T3R Elemento|Gerardo Ortiz,34nbQa7Hug9DYkRJpfKNFv|4J13m9IZh03PEhoxAxRhXO,The Green Trip,1KrCvwoIRQ18824qcMFb4F,70,2:54,1,11/16/2018,album,USE7D1800127,2
9889,9890,Brillo,5gS11pL9yQcnKrzbmliOwh,Natanael Cano,0elWFr7TW8piilVRYJUe4P,NataKong,2irmTvrbuG1ox2Qa6R8J1L,70,2:34,1,4/8/2022,album,USWL12200194,1
9893,9894,San Pedro,3meHMCLIeGhw46OBAmC0AC,Ganggy|Victor Mendivil,5DyLJzaY28nfyYFYu5a7Py|5YqI7p8zYsOpKJtjxYdOce,San Pedro,1isqlLWYMmokfCrK1uDSBL,70,3:18,1,4/18/2024,single,USA2P2421036,1
9898,9899,Cositas Que Haciamos (feat. Farruko),6V2Y0Anhyq538bSVyWVt47,Musicologo Y Menes|Farruko,0xf0KaVp6AMWgesiBh6fee|329e4yvIujISKGKz1BZZbO,"Los De La Nazza the Collection, Vol. 1",7CKHPPrMD8WHybUhrykhjk,70,4:04,1,11/18/2013,album,TCABR1393660,2
9907,9908,Ayer Me Llamó Mi Ex,3ef2QlCUWO29UvqJaU3MUi,KHEA|Lenny Santos,4m6ubhNsdwF4psNf3R8kwR|4bODqflR0Wo3i3fCwwCIPq,Ayer Me Llamó Mi Ex,3ryXum3u0sEV2f6oBHXI22,70,3:26,1,8/20/2020,single,USLD91728247,2
9908,9909,Lollipop,3cDyocF0Ibdfs1SFQk5cLZ,Darell,1TtXnWcUs0FCkaZDPGYHdf,EVERYBODY GO TO THE DISCOTEK,11UJfH39O0VqLiQGLW0D0e,70,3:19,1,7/28/2023,album,USSD12300307,2
9915,9916,Coffin,5vDNippoMr52KpXBO9b9KQ,Lil Yachty,6icQOAFXDZKsumw3YXyusw,Lil Boat 3.5,6ufaA5YvSGK3E9KnRFYvvo,70,1:29,1,11/27/2020,album,USUG12001669,13
9916,9917,3500 (feat. Future & 2 Chainz),1SGt65i9AnXYdDQt1AtDRH,Travis Scott|Future|2 Chainz,0Y5tJX1MQlPlqiwlOH1tJY|1RyvyyTE3xzB2ZywiAwp0i|...,Rodeo,4PWBTB6NYSKQwfo79I3prg,70,7:41,1,9/4/2015,album,USSM11500911,2
9919,9920,Bangarang (feat. Sirah),6VRhkROS2SZHGlp0pxndbJ,Skrillex|Sirah,5he5w2lnU9x7JFhnwcekXX|3oAazIwC0nAYkOKVQPUC38,Bangarang EP,5XJ2NeBxZP3HFM8VoBQEUe,70,3:35,1,12/27/2011,single,USAT21104243,10
9923,9924,Romance Fdp,28m43rfXTN3vJseUZbenTY,DJ Voltz|Mc Jhey|FreesTyle Sounds,6q6fM6TNV6HBQ6vOidAfLo|34giN3qeTOdgDSJIdtIMdm|...,Romance Fdp,0mxdIehDYd7hCDrdk2mhUT,70,1:31,1,10/12/2024,single,GXD7G2263072,1
9936,9937,Sorriso no Rosto,3kBYuWrGtx1tSHjzr0vlZh,Mc IG|Murillo e LT no Beat|DJ Glenner,2q9wk5fkeU2C9CgCKdh4AN|0KcbRunfjZHfwEnEgd1Dy6|...,Sorriso no Rosto,7uA5fxR9xIiO5rXx4pkchd,70,2:28,1,5/28/2024,single,BRWMB2400738,95
9942,9943,Não Bebo Não Fumo Mais,361DsT1rBpJKIYVJNSP0pk,MC Ryan SP|Mc IG|Mc Don Juan|Boladin 211|MC LU...,75i9GaW2MJUgt4BkdUnuUY|2q9wk5fkeU2C9CgCKdh4AN|...,Não Bebo Não Fumo Mais,1PUtB9es4WIqcEJb5LnmDr,70,8:40,1,1/21/2025,single,BRWMB2500046,19
9943,9944,Nois não é Migo 2,1sOekKvVvsXudILOOnNasw,MC Ryan SP|MC GP|Boladin 211|Mc Negão Original...,75i9GaW2MJUgt4BkdUnuUY|5s27i7oqhNWIcE4HeoVdq0|...,Nois não é Migo 2,0HtgcDGbckZvWDgqGO1RB9,70,6:24,1,11/7/2024,single,BRWMB2401808,11
9947,9948,Tropa do Sem K.O,02I0Nm97YdmZ8teGFcIHEy,MC Joãozinho VT|MC Tuto|MC Vine7|MC Ryan SP|Mc...,6XFc29m1ptfUNmaa1UTuBT|6aoGgTKGqtsjj48ymcNs4Z|...,Tropa do Sem K.O,5SM8mR0LUO5ajfRTGAtU5e,70,6:16,1,9/3/2024,single,BCSOR2400071,1
9948,9949,Mesma História,54FV2rMVwLusAVnzROB0c1,Orochi|Caio Luccas|Pedro Lotto|Mainstreet|Gald...,3rfM2cGqF6DB0kUyytMkXx|1a3fr7NdeBT4JlGj6YlbDL|...,Vida Cara (Deluxe),3KvM71DjnZsDr0dxppQNjT,70,2:43,1,10/6/2023,album,BCM9A2300083,1
9949,9950,Rolé na Favela de Nave,1m5nbZiPpCIi9J2irLNoxh,Oruam|Didi|Dj Lc da Roça|MC K9|MC Smith|Mainst...,4yGgbQJMq9orWypwqtdzYT|15bTpg6S948FjSiOhB7eXi|...,Rolé na Favela de Nave,1m42RnQb6QKdchutofb4mH,70,3:12,1,1/30/2024,single,BCM9A2400002,1
9950,9951,ПОВОД,1SUguUEQfQokc535Ye7ttR,MORGENSHTERN,0XNKQFs2Ewb3y0VsFUFc5l,ALISHER,4Y8nQDihhjaKefzE3rmoAM,70,2:33,1,2/14/2025,single,FR2X42536158,1
9952,9953,Wunder,4b3W0IbHDwHCvjSs708Tr4,AYLIVA|Apache 207,2rEVnwCPBeGkWMv425KoG1|1qQLhymHXFPtP5U8KNKsm6,In Liebe,3cB6tCOD8fqXuYwbpcrcdV,70,2:56,1,8/16/2024,album,DEA622401272,4
9953,9954,Reggaeton Champagne,7yIIeKUxTpn36X6CFJhgEi,Bellakath|Dani Flow,4yjm4SvYqC5FFuLbB6TyHr|1yX62RHdYysNcIrO33WQxJ,Kittyponeo,2u2IVr3kVR13lr517rvcjM,70,2:39,1,10/5/2023,album,BK4DA2319233,2
9955,9956,X1,0dcHD9QhnWRA41zoLnC83X,MC Cabelinho|Dallass,1WQBwwssN6r8DSjUlkyUGW|4LAFtDzlQM89xov636hMVv,LITTLE HAIR,1KAZ4CtfGW7JgVvh6lq30V,70,3:08,1,12/20/2021,album,QZTVM2103308,1
9957,9958,Poesia Acústica #2: Sobre Nós,6gFQhcUOhNXaq965kYEdsH,Delacruz|Maria|Ducon|Luiz Lins|Diomedes Chinas...,1MzXJ8AaHdidMAnjgcahS4|1fcS44jH4wr0qwxSVdxWyX|...,Poesia Acústica,6vbpX6UMYzBifE5fCJjB3Z,70,7:51,1,10/7/2024,compilation,BRUK01800001,2
9958,9959,Poesia Acústica #6 Era uma Vez,5JC2ezFSbkVi4Js4byzKoj,MC Cabelinho|Bob do Contra|Azzy|Filipe Ret|Dud...,1WQBwwssN6r8DSjUlkyUGW|4DITWCDQL8b3VZTBYpNDR9|...,Poesia Acústica,6vbpX6UMYzBifE5fCJjB3Z,70,9:37,1,10/7/2024,compilation,BRUK01800007,2
9966,9967,"Nasty Girl (feat. Diddy, Nelly, Jagged Edge & ...",4GIsskMpViPkt0uzPJTJSp,The Notorious B.I.G.|Avery Storm|Diddy|Jagged ...,5me0Irg2ANcsgc93uaYrpb|79OSA519ScnPY0MVDpu8ZV|...,Duets: The Final Chapter,2M6rjUsC2T3KJ8Ku2uTTQG,70,4:46,1,12/13/2005,album,USBB10500008,8
9967,9968,When It Rains It Pours,1cA2LExLTdhHLL0FmXoc57,50 Cent,3q7HBObVc0L8jNeTe5Gofh,Get Rich Or Die Tryin'- The Original Motion Pi...,5D2CHiTlb8MXWJsZWXjkZf,70,4:02,1,1/1/2005,compilation,USUM70504815,3
9968,9969,Beckham,60lAoxcyDvRbcNY82VEoEA,Dee Billz|Kyle Richh|Kai Swervo|KJ Swervo|41,2fBU7rOViK7ywwHCIYEa7h|0hF6lbAjRsq4svrQUr5sgU|...,Beckham,1GNQ8Lr4qLa6XTTm7Xuwgw,70,2:04,1,7/3/2024,single,USA2P2442379,7
9973,9974,Dial Drunk,0caJ2wkqp4UmXBwdR2JvB5,Noah Kahan,2RQXRUsr4IW1f3mKyKsy4B,Stick Season (We'll All Be Here Forever),1pb3je8gXTs5dpRRTKhHRC,70,3:33,1,6/9/2023,album,USUM72307683,8
9986,9987,Ponte Bonita,50tfayMP8ZnSiV1sPM48qD,Cris Mj,1Yj5Xey7kTwvZla8sqdsdE,Partyson,5v3JncpvWjEDrGDeHJw9TL,70,3:13,1,11/9/2023,album,QMFMF2314108,1

In [25]:
# multi-level 
sorted_albums = df.sort_values(
    by=["artist_names", "popularity", "rank"],
    ascending=[True, False, True]
)
sorted_albums

,rank,track_name,track_id,artist_names,artist_ids,album_name,album_id,popularity,duration,explicit,release_date,album_type,isrc,copies
6202,6203,RISADA CHUCK 01 - Super Slowed,2iRiWUoB7tNnG23KlM3Ui7,#NAME?,3uA4unR7LBOcqjpbOeCs0Y,RISADA CHUCK 01,7lolzbhq4moSJPfFpdosl5,73,2:10,1,8/26/2024,single,CA5KR2491417,1
2546,2547,Antarctica,5UGAXwbA17bUC0K9uquGY2,$uicideboy$,1VPmR4DJC1PlOtd0IADAO0,Antarctica,2uSbIkeZ2TszTDfbzmkhyL,77,2:06,1,1/26/2016,single,QM8DG1600530,4
2547,2548,"...And to Those I Love, Thanks for Sticking Ar...",30QR0ndUdiiMQMA9g1PGCm,$uicideboy$,1VPmR4DJC1PlOtd0IADAO0,Stop Staring At the Shadows,7rKmLxCFlmtIxGpX4HYgs4,77,2:48,1,2/14/2020,album,QZAPK1900020,24
2548,2549,1000 Blunts,09riz9pAPJyYYDVynE5xxY,$uicideboy$,1VPmR4DJC1PlOtd0IADAO0,"Sing Me a Lullaby, My Sweet Temptation",3elJRIffdqvypuxoDND2Q3,77,2:55,1,7/29/2022,album,QZAPK2000271,1
3083,3084,For the Last Time,240audWazVjwvwh7XwfSZE,$uicideboy$,1VPmR4DJC1PlOtd0IADAO0,For the Last Time,4CcyRnFW6Vgf372ca3xFGR,76,2:36,1,9/5/2017,single,QM8DG1703420,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7738,7739,WU,3JtDg3OPwkuxbuSV1UxcFz,張哲瀚,1DMI6oQrrt8rVMVN83jXA7,WU,3irBioAWkaAO3ZtDq727OM,71,3:23,0,6/28/2025,single,TWU712505003,2
9221,9222,地球陌生人 Earth Stranger,1lx9uwqLp0EI3YcmzJjwVI,張哲瀚,1DMI6oQrrt8rVMVN83jXA7,地球陌生人 Earth Stranger,3krzg1oAdXncFkPZphmZWC,70,5:20,0,4/15/2025,single,TWU712502563,2
9714,9715,八方來財,7jm2PueKmv4EOHfdbdXMKT,攬佬SKAI ISYOURGOD,4LUmhH4A1lvFljre6d00NI,八方來財,5vYWbmWrSSBskg28cRmcjg,70,2:53,0,8/20/2024,album,HKE022272921,1
9343,9344,カワキヲアメク,3kUWZiVYJ4YQOl0u7Y1Og8,美波,1KXJUpTiNeMv93LrJbbm7G,カワキヲアメク,6R5yCaIbIwK9IQJErCb0FV,70,4:11,0,1/30/2019,single,JPVI01817011,2
3212,3213,It's Going Down Now,3znIACSXPLn3HFCf7moZ28,高橋あず美|Lotus Juice|アトラスサウンドチーム|ATLUS GAME MUSIC,4VeqFgWkP7P9eEGwzPuXcM|0HM4KuHUJ5ww5DdOGi3FEf|...,Persona 3 Reload Original Soundtrack,20Bf2RVERC5Bc2eo3vyvJv,76,3:06,0,4/24/2024,album,JPK652300130,4

In [29]:
df.groupby("artist_names").count()

,rank,track_name,track_id,artist_ids,album_name,album_id,popularity,duration,explicit,release_date,album_type,isrc,copies
artist_names,,,,,,,,,,,,,
#NAME?,1,1,1,1,1,1,1,1,1,1,1,1,1
$uicideboy$,16,16,16,16,16,16,16,16,16,16,16,16,16
$uicideboy$|Pouya,1,1,1,1,1,1,1,1,1,1,1,1,1
$werve,2,2,2,2,2,2,2,2,2,2,2,2,2
$werve|FXRCE|Mc Denny,2,2,2,2,2,2,2,2,2,2,2,2,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...
ヨルシカ,3,3,3,3,3,3,3,3,3,3,3,3,3
張哲瀚,3,3,3,3,3,3,3,3,3,3,3,3,3
攬佬SKAI ISYOURGOD,1,1,1,1,1,1,1,1,1,1,1,1,1
美波,1,1,1,1,1,1,1,1,1,1,1,1,1
高橋あず美|Lotus Juice|アトラスサウンドチーム|ATLUS GAME MUSIC,1,1,1,1,1,1,1,1,1,1,1,1,1